// Copyright (c) Microsoft. All rights reserved.

namespace Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk;

using System;
using System.Collections.Generic;
using System.Diagnostics.Metrics;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.AI.OpenAI;
using ChatCompletion;
using Extensions.Logging;
using Extensions.Logging.Abstractions;
using FunctionCalling;
using FunctionCalling.Extensions;
using Prompt;
using SemanticKernel.AI;
using SemanticKernel.AI.ChatCompletion;
using SemanticKernel.AI.TextCompletion;
using ChatMessage = Azure.AI.OpenAI.ChatMessage;

#pragma warning disable CA2208 // Instantiate argument exceptions correctly


/// <summary>
/// Base class for AI clients that provides common functionality for interacting with OpenAI services.
/// </summary>
public abstract class ClientBase
{
    private const int MaxResultsPerPrompt = 128;
    private const string NameProperty = "Name";
    private const string ArgumentsProperty = "Arguments";


    // Prevent external inheritors
    protected private ClientBase(ILoggerFactory? loggerFactory = null) => Logger = loggerFactory is not null ? loggerFactory.CreateLogger(GetType()) : NullLogger.Instance;

    /// <summary>
    /// Model Id or Deployment Name
    /// </summary>
    protected private string DeploymentOrModelName { get; set; } = string.Empty;

    /// <summary>
    /// OpenAI / Azure OpenAI Client
    /// </summary>
    protected private abstract OpenAIClient Client { get; }

    /// <summary>
    /// Logger instance
    /// </summary>
    protected private ILogger Logger { get; set; }

    /// <summary>
    /// Storage for AI service attributes.
    /// </summary>
    protected private Dictionary<string, string> InternalAttributes = new();

    /// <summary>
    /// Instance of <see cref="Meter"/> for metrics.
    /// </summary>
    private static readonly Meter s_meter = new("Microsoft.SemanticKernel.Connectors.AI.OpenAI");

    /// <summary>
    /// Instance of <see cref="Counter{T}"/> to keep track of the number of prompt tokens used.
    /// </summary>
    private static readonly Counter<int> s_promptTokensCounter =
        s_meter.CreateCounter<int>(
            "sk.connectors.openai.tokens.prompt",
            "{token}",
            "Number of prompt tokens used");

    /// <summary>
    /// Instance of <see cref="Counter{T}"/> to keep track of the number of completion tokens used.
    /// </summary>
    private static readonly Counter<int> s_completionTokensCounter =
        s_meter.CreateCounter<int>(
            "sk.connectors.openai.tokens.completion",
            "{token}",
            "Number of completion tokens used");

    /// <summary>
    /// Instance of <see cref="Counter{T}"/> to keep track of the total number of tokens used.
    /// </summary>
    private static readonly Counter<int> s_totalTokensCounter =
        s_meter.CreateCounter<int>(
            "sk.connectors.openai.tokens.total",
            "{token}",
            "Number of tokens used");


    /// <summary>
    /// Creates completions for the prompt and settings.
    /// </summary>
    /// <param name="text">The prompt to complete.</param>
    /// <param name="requestSettings">Request settings for the completion API</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>Completions generated by the remote model</returns>
    protected private async Task<IReadOnlyList<ITextResult>> InternalGetTextResultsAsync(
        string text,
        PromptExecutionSettings? requestSettings,
        CancellationToken cancellationToken = default)
    {
        var textRequestSettings = OpenAIPromptExecutionSettings.FromRequestSettings(requestSettings, OpenAIPromptExecutionSettings.DefaultTextMaxTokens);

        ValidateMaxTokens(textRequestSettings.MaxTokens);
        var options = CreateCompletionsOptions(text, textRequestSettings);

        Response<Completions>? response = await RunRequestAsync<Response<Completions>?>(
            () => Client.GetCompletionsAsync(DeploymentOrModelName, options, cancellationToken)).ConfigureAwait(false);

        if (response is null)
        {
            throw new KernelException("Text completions null response");
        }

        var responseData = response.Value;

        if (responseData.Choices.Count == 0)
        {
            throw new KernelException("Text completions not found");
        }

        CaptureUsageDetails(responseData.Usage);

        return responseData.Choices.Select(choice => new TextResult(responseData, choice)).ToList();
    }


    protected private async IAsyncEnumerable<T> InternalGetTextStreamingUpdatesAsync<T>(
        string prompt,
        PromptExecutionSettings? requestSettings,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var textRequestSettings = OpenAIPromptExecutionSettings.FromRequestSettings(requestSettings, OpenAIPromptExecutionSettings.DefaultTextMaxTokens);

        ValidateMaxTokens(textRequestSettings.MaxTokens);

        var options = CreateCompletionsOptions(prompt, textRequestSettings);

        Response<StreamingCompletions>? response = await RunRequestAsync<Response<StreamingCompletions>>(
            () => Client.GetCompletionsStreamingAsync(DeploymentOrModelName, options, cancellationToken)).ConfigureAwait(false);

        using var streamingChatCompletions = response.Value;
        Dictionary<string, object> responseMetadata = GetResponseMetadata(streamingChatCompletions);

        var choiceIndex = 0;

        await foreach (var choice in streamingChatCompletions.GetChoicesStreaming(cancellationToken).ConfigureAwait(false))
        {
            await foreach (var update in choice.GetTextStreaming(cancellationToken).ConfigureAwait(false))
            {
                // If the provided T is a string, return the completion as is
                if (typeof(T) == typeof(string))
                {
                    yield return (T)(object)update;

                    continue;
                }

                // If the provided T is an specialized class of StreamingContent interface
                if (typeof(T) == typeof(StreamingTextContent) ||
                    typeof(T) == typeof(StreamingContent))
                {
                    yield return (T)(object)new StreamingTextContent(update, choiceIndex, update, responseMetadata);

                    continue;
                }

                throw new NotSupportedException($"Type {typeof(T)} is not supported");
            }
            choiceIndex++;
        }
    }


    private static Dictionary<string, object> GetResponseMetadata(StreamingCompletions streamingChatCompletions) => new()
    {
        { $"{nameof(StreamingCompletions)}.{nameof(streamingChatCompletions.PromptFilterResults)}", streamingChatCompletions.PromptFilterResults }
    };


    private static Dictionary<string, object> GetResponseMetadata(StreamingChatCompletions streamingChatCompletions) => new()
    {
        { $"{nameof(StreamingChatCompletions)}.{nameof(streamingChatCompletions.PromptFilterResults)}", streamingChatCompletions.PromptFilterResults }
    };


    /// <summary>
    /// Generates an embedding from the given <paramref name="data"/>.
    /// </summary>
    /// <param name="data">List of strings to generate embeddings for</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <returns>List of embeddings</returns>
    protected private async Task<IList<ReadOnlyMemory<float>>> InternalGetEmbeddingsAsync(
        IList<string> data,
        CancellationToken cancellationToken = default)
    {
        List<ReadOnlyMemory<float>> result = new(data.Count);

        foreach (var options in data.Select(text => new EmbeddingsOptions(text)))
        {
            Response<Embeddings>? response = await RunRequestAsync<Response<Embeddings>?>(
                () => Client.GetEmbeddingsAsync(DeploymentOrModelName, options, cancellationToken)).ConfigureAwait(false);

            if (response is null)
            {
                throw new KernelException("Text embedding null response");
            }

            if (response.Value.Data.Count == 0)
            {
                throw new KernelException("Text embedding not found");
            }

            result.Add(response.Value.Data[0].Embedding.ToArray());
        }

        return result;
    }


    /// <summary>
    /// Generate a new chat message
    /// </summary>
    /// <param name="chat">Chat history</param>
    /// <param name="requestSettings">AI request settings</param>
    /// <param name="cancellationToken">Async cancellation token</param>
    /// <returns>Generated chat message in string format</returns>
    protected private async Task<IReadOnlyList<IChatResult>> InternalGetChatResultsAsync(
        ChatHistory chat,
        PromptExecutionSettings? requestSettings,
        CancellationToken cancellationToken = default)
    {
        Verify.NotNull(chat);

        var chatRequestSettings = (OpenAIPromptExecutionSettings)(requestSettings is FunctionCallRequestSettings
            ? requestSettings
            : OpenAIPromptExecutionSettings.FromRequestSettings(requestSettings));

        ValidateMaxTokens(chatRequestSettings.MaxTokens);
        var chatOptions = CreateChatCompletionsOptions(chatRequestSettings!, chat);

        List<string>? functionNames = chatOptions.Functions?.Select(f => f.Name).ToList();
        Response<ChatCompletions>? response = await RunRequestAsync<Response<ChatCompletions>?>(
            () => Client.GetChatCompletionsAsync(DeploymentOrModelName, chatOptions, cancellationToken)).ConfigureAwait(false);

        if (response is null)
        {
            throw new KernelException("Chat completions null response");
        }

        var responseData = response.Value;

        if (responseData.Choices.Count == 0)
        {
            throw new KernelException("Chat completions not found");
        }

        CaptureUsageDetails(responseData.Usage);

        if (functionNames is null)
        {
            return responseData.Choices.Select(chatChoice => new ChatResult(responseData, chatChoice)).ToList();
        }

        if (!responseData.IsFunctionCallResponse(functionNames))
        {
            return responseData.Choices.Select(chatChoice => new ChatResult(responseData, chatChoice)).ToList();
        }
        return responseData.Choices.Select(choice => choice.IsFunctionCall(functionNames)
                ? new ChatResult(responseData, choice, true)
                : new ChatResult(responseData, choice)).Cast<IChatResult>()
            .ToList();
    }


    protected private async IAsyncEnumerable<T> InternalGetChatStreamingUpdatesAsync<T>(
        IEnumerable<SemanticKernel.AI.ChatCompletion.ChatMessage> chat,
        PromptExecutionSettings? requestSettings,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        Verify.NotNull(chat);

        var chatRequestSettings = OpenAIPromptExecutionSettings.FromRequestSettings(requestSettings);

        ValidateMaxTokens(chatRequestSettings.MaxTokens);

        var options = CreateChatCompletionsOptions(chatRequestSettings, chat);

        Response<StreamingChatCompletions>? response = await RunRequestAsync<Response<StreamingChatCompletions>>(
            () => Client.GetChatCompletionsStreamingAsync(DeploymentOrModelName, options, cancellationToken)).ConfigureAwait(false);

        if (response is null)
        {
            throw new KernelException("Chat completions null response");
        }

        using var streamingChatCompletions = response.Value;
        Dictionary<string, object> responseMetadata = GetResponseMetadata(streamingChatCompletions);

        var choiceIndex = 0;

        await foreach (var choice in streamingChatCompletions.GetChoicesStreaming(cancellationToken).ConfigureAwait(false))
        {
            await foreach (var chatMessage in choice.GetMessageStreaming(cancellationToken).ConfigureAwait(false))
            {
                if (typeof(T) == typeof(string))
                {
                    yield return (T)(object)chatMessage.Content;

                    continue;
                }

                // If the provided T is an specialized class of StreamingResultChunk interface
                if (typeof(T) == typeof(StreamingChatContent) ||
                    typeof(T) == typeof(StreamingContent))
                {
                    yield return (T)(object)new StreamingChatContent(chatMessage, choiceIndex, responseMetadata);

                    continue;
                }

                throw new NotSupportedException($"Type {typeof(T)} is not supported");
            }
            choiceIndex++;
        }
    }


    /// <summary>
    /// Create a new empty chat instance
    /// </summary>
    /// <param name="instructions">Optional chat instructions for the AI service</param>
    /// <returns>Chat object</returns>
    protected private static OpenAIChatHistory InternalCreateNewChat(string? instructions = null) => new(instructions);


    /// <summary>
    /// Create a new chat instance based on chat history.
    /// </summary>
    /// <param name="chatHistory">Instance of <see cref="ChatHistory"/>.</param>
    /// <returns>Chat object</returns>
    protected private static OpenAIChatHistory InternalCreateNewChat(ChatHistory chatHistory) => new(chatHistory);


    protected private async Task<IReadOnlyList<ITextResult>> InternalGetChatResultsAsTextAsync(
        string text,
        PromptExecutionSettings? requestSettings,
        CancellationToken cancellationToken = default)
    {
        ChatHistory chat = PrepareChatHistory(text, requestSettings, out var chatSettings);

        return (await InternalGetChatResultsAsync(chat, chatSettings, cancellationToken).ConfigureAwait(false))
            .OfType<ITextResult>()
            .ToList();
    }


    protected private void AddAttribute(string key, string? value)
    {
        if (!string.IsNullOrEmpty(value))
        {
            InternalAttributes.Add(key, value!);
        }
    }


    private static OpenAIChatHistory PrepareChatHistory(string text, PromptExecutionSettings? requestSettings, out OpenAIPromptExecutionSettings settings)
    {
        settings = OpenAIPromptExecutionSettings.FromRequestSettings(requestSettings);

        if (XmlPromptParser.TryParse(text, out List<PromptNode> nodes) && ChatPromptParser.TryParse(nodes, out var chatHistory))
        {
            return InternalCreateNewChat(chatHistory);
        }

        var chat = InternalCreateNewChat(settings.ChatSystemPrompt);
        chat.AddUserMessage(text);
        return chat;
    }


    private static CompletionsOptions CreateCompletionsOptions(string text, OpenAIPromptExecutionSettings requestSettings)
    {
        if (requestSettings.ResultsPerPrompt is < 1 or > MaxResultsPerPrompt)
        {
            throw new ArgumentOutOfRangeException($"{nameof(requestSettings)}.{nameof(requestSettings.ResultsPerPrompt)}", requestSettings.ResultsPerPrompt, $"The value must be in range between 1 and {MaxResultsPerPrompt}, inclusive.");
        }

        var options = new CompletionsOptions
        {
            Prompts = { text.Replace("\r\n", "\n") }, // normalize line endings
            MaxTokens = requestSettings.MaxTokens,
            Temperature = (float?)requestSettings.Temperature,
            NucleusSamplingFactor = (float?)requestSettings.TopP,
            FrequencyPenalty = (float?)requestSettings.FrequencyPenalty,
            PresencePenalty = (float?)requestSettings.PresencePenalty,
            Echo = false,
            ChoicesPerPrompt = requestSettings.ResultsPerPrompt,
            GenerationSampleCount = requestSettings.ResultsPerPrompt,
            LogProbabilityCount = null,
            User = null
        };

        foreach (KeyValuePair<int, int> keyValue in requestSettings.TokenSelectionBiases)
        {
            options.TokenSelectionBiases.Add(keyValue.Key, keyValue.Value);
        }

        if (requestSettings.StopSequences is { Count: > 0 })
        {
            foreach (var s in requestSettings.StopSequences)
            {
                options.StopSequences.Add(s);
            }
        }

        return options;
    }


    internal static ChatCompletionsOptions CreateChatCompletionsOptions(OpenAIPromptExecutionSettings requestSettings, IEnumerable<SemanticKernel.AI.ChatCompletion.ChatMessage> chatHistory)
    {
        if (requestSettings.ResultsPerPrompt is < 1 or > MaxResultsPerPrompt)
        {
            throw new ArgumentOutOfRangeException($"{nameof(requestSettings)}.{nameof(requestSettings.ResultsPerPrompt)}", requestSettings.ResultsPerPrompt, $"The value must be in range between 1 and {MaxResultsPerPrompt}, inclusive.");
        }

        var options = requestSettings switch
        {
            FunctionCallRequestSettings functionCallRequestSettings => new ChatCompletionsOptions
            {
                MaxTokens = functionCallRequestSettings.MaxTokens,
                Temperature = (float?)functionCallRequestSettings.Temperature,
                NucleusSamplingFactor = (float?)functionCallRequestSettings.TopP,
                FrequencyPenalty = (float?)functionCallRequestSettings.FrequencyPenalty,
                PresencePenalty = (float?)functionCallRequestSettings.PresencePenalty,
                ChoiceCount = requestSettings.ResultsPerPrompt,
                FunctionCall = functionCallRequestSettings.TargetFunctionCall,
                Functions = functionCallRequestSettings.CallableFunctions
            },
            _ => new ChatCompletionsOptions
            {
                MaxTokens = requestSettings.MaxTokens,
                Temperature = (float?)requestSettings.Temperature,
                NucleusSamplingFactor = (float?)requestSettings.TopP,
                FrequencyPenalty = (float?)requestSettings.FrequencyPenalty,
                PresencePenalty = (float?)requestSettings.PresencePenalty,
                ChoiceCount = requestSettings.ResultsPerPrompt
            }
        };

        foreach (KeyValuePair<int, int> keyValue in requestSettings.TokenSelectionBiases)
        {
            options.TokenSelectionBiases.Add(keyValue.Key, keyValue.Value);
        }

        if (requestSettings.StopSequences is { Count: > 0 })
        {
            foreach (var s in requestSettings.StopSequences)
            {
                options.StopSequences.Add(s);
            }
        }

        foreach (var message in chatHistory)
        {
            var azureMessage = new ChatMessage(new ChatRole(message.Role.Label), message.Content);

            if (message.AdditionalProperties?.TryGetValue(NameProperty, out var name) is true)
            {
                azureMessage.Name = name;

                if (message.AdditionalProperties?.TryGetValue(ArgumentsProperty, out var arguments) is true)
                {
                    azureMessage.FunctionCall = new FunctionCall(name, arguments);
                }
            }

            options.Messages.Add(azureMessage);
        }
        return options;
    }


    private static void ValidateMaxTokens(int? maxTokens)
    {
        if (maxTokens.HasValue && maxTokens < 1)
        {
            throw new KernelException($"MaxTokens {maxTokens} is not valid, the value must be greater than zero");
        }
    }


    private static async Task<T> RunRequestAsync<T>(Func<Task<T>> request)
    {
        try
        {
            return await request.Invoke().ConfigureAwait(false);
        }
        catch (RequestFailedException e)
        {
            throw e.ToHttpOperationException();
        }
    }


    /// <summary>
    /// Captures usage details, including token information.
    /// </summary>
    /// <param name="usage">Instance of <see cref="CompletionsUsage"/> with usage details.</param>
    private void CaptureUsageDetails(CompletionsUsage usage)
    {
        Logger.LogInformation(
            "Prompt tokens: {PromptTokens}. Completion tokens: {CompletionTokens}. Total tokens: {TotalTokens}",
            usage.PromptTokens, usage.CompletionTokens, usage.TotalTokens);

        s_promptTokensCounter.Add(usage.PromptTokens);
        s_completionTokensCounter.Add(usage.CompletionTokens);
        s_totalTokensCounter.Add(usage.TotalTokens);
    }
}
