// Copyright (c) Microsoft. All rights reserved.

namespace Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk;

using System;
using System.Text.Json.Serialization;
using Azure.AI.OpenAI;
using SemanticKernel.AI.ChatCompletion;


/// <summary>
/// Chat message representation from Semantic Kernel ChatMessageBase Abstraction
/// </summary>
public class SKChatMessage : ChatMessageBase
{
    private readonly ChatMessage? _message;

    /// <summary>
    ///  The name of the function call if the message is a function call.
    /// </summary>
    [JsonPropertyName("function")]
    public string? FunctionName { get; }


    /// <summary>
    /// Initializes a new instance of the <see cref="SKChatMessage"/> class.
    /// </summary>
    /// <param name="message">OpenAI SDK chat message representation</param>
    public SKChatMessage(ChatMessage message)
        : base(new AuthorRole(message.Role.ToString()), message.Content)
    {
        _message = message;
        FunctionName = message.Name;
    }


    /// <summary>
    /// Initializes a new instance of the <see cref="SKChatMessage"/> class.
    /// </summary>
    /// <param name="role">Role of the author of the message.</param>
    /// <param name="content">Content of the message.</param>
    /// <param name="functionName">The name of the function that should be called, as generated by the model.</param>
    public SKChatMessage(string role, string content, string? functionName = null)
        : base(new AuthorRole(role), content) => FunctionName = functionName;


    /// <summary>
    /// Exposes the underlying OpenAI SDK function call chat message representation
    /// </summary>
    public FunctionCall FunctionCall
        => _message?.FunctionCall ?? throw new NotSupportedException("Function call is not supported");
}
